CREATE DATABASE BDGestorPagosCAEZ
 use BDGestorPagosCAEZ
-- TABLA Turno
CREATE TABLE Turno(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);

-- TABLA Grado
CREATE TABLE Grado(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);

-- TABLA TipoDocumento
CREATE TABLE TipoDocumento(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);

-- TABLA TipoPago 
CREATE TABLE TipoPago(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);

-- TABLA Mes 
CREATE TABLE Mes(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);

-- TABLA Direccion
CREATE TABLE Direccion(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(200) NOT NULL
);

-- TABLA Cargo
CREATE TABLE Cargo(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);

-- TABLA Multa
CREATE TABLE Multa(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);

-- TABLA Administrador 
CREATE TABLE Administrador(
    Id BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR (50) NOT NULL,
    Apellido VARCHAR (50) NOT NULL,
    IdCargo TINYINT NOT NULL FOREIGN KEY REFERENCES Cargo(Id),
    Correo VARCHAR(50) NOT NULL,
    Pass VARCHAR (200) NOT NULL
);

-- TABLA Encargado 
CREATE TABLE Encargado(
    Id BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR (50) NOT NULL,
    Apellido VARCHAR (50) NOT NULL,
    IdTipoDoc TINYINT NOT NULL FOREIGN KEY REFERENCES TipoDocumento(Id),
    NumeroDocumento VARCHAR(50) NOT NULL,
    Telefono VARCHAR(50) NOT NULL,
    Direccion TINYINT NOT NULL FOREIGN KEY REFERENCES Direccion(Id),
    Parentezco VARCHAR (50)
);

-- TABLA Alumno
CREATE TABLE Alumno(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR (50) NOT NULL,
    Apellido VARCHAR (50) NOT NULL,
    IdGrado TINYINT NOT NULL FOREIGN KEY REFERENCES Grado(Id),
    IdTipoDoc TINYINT NOT NULL FOREIGN KEY REFERENCES TipoDocumento(Id),
    NumeroDocumento VARCHAR(50) NOT NULL,
    IdEncargado BIGINT NOT NULL FOREIGN KEY REFERENCES Encargado(Id),
    IdTurno TINYINT NOT NULL FOREIGN KEY REFERENCES Turno(Id)
);

-- TABLA Factura
CREATE TABLE Factura(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    IdAlumno INT NOT NULL FOREIGN KEY REFERENCES Alumno(Id),
    IdMes TINYINT NOT NULL FOREIGN KEY REFERENCES Mes(Id),
    FechaPago DATE NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL,
    IdAdministrador BIGINT NOT NULL FOREIGN KEY REFERENCES Administrador(Id),
    Multa DECIMAL(10, 2) NOT NULL
);

-- TABLA Fondo
CREATE TABLE Fondo(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    MontoTotal DECIMAL(10, 2) NOT NULL
);

-- TABLA OtrosFondos
CREATE TABLE OtrosFondos(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(100) NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL,
    Fecha DATE NOT NULL,
    IdAdministrador BIGINT NOT NULL FOREIGN KEY REFERENCES Administrador(Id)
);
