-- TABLA Cargo-- TABLA Cargo
CREATE DATABASE CAEZ
USE CAEZ
-- TABLA Cargo
CREATE TABLE Cargo(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);
GO
-- TABLA Direccion
CREATE TABLE Direccion(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(200) NOT NULL
);
GO
-- TABLA Turno
CREATE TABLE Turno(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);
GO
-- TABLA Grado
CREATE TABLE Grado(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);
GO
-- TABLA TipoDocumento
CREATE TABLE TipoDocumento(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);
GO
-- TABLA TipoPago
CREATE TABLE TipoPago(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(80) NOT NULL
);
GO
-- TABLA Parentezco
CREATE TABLE Parentezco(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);
GO
-- TABLA Mes
CREATE TABLE Mes(
    Id TINYINT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL
);
GO
-- TABLA Administrador
CREATE TABLE Administrador(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    IdCargo TINYINT NOT NULL FOREIGN KEY REFERENCES Cargo(Id),
    Telefono VARCHAR(50) NOT NULL,
    Pass VARCHAR(200) NOT NULL
);
GO
-- TABLA AdministradorEncargado
CREATE TABLE Encargado(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    IdTipoDoc TINYINT NOT NULL FOREIGN KEY REFERENCES TipoDocumento(Id),
    NumeroDocumento VARCHAR(50) NOT NULL,
    Telefono VARCHAR(50) NOT NULL,
    Direccion TINYINT NOT NULL FOREIGN KEY REFERENCES Direccion(Id),
    IdParentezco TINYINT NOT NULL FOREIGN KEY REFERENCES Parentezco(Id),
    IdAdministrador INT NOT NULL FOREIGN KEY REFERENCES Administrador(Id)
);
GO
-- TABLA Alumno
CREATE TABLE Alumno(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    IdGrado TINYINT NOT NULL FOREIGN KEY REFERENCES Grado(Id),
    IdTipoDoc TINYINT NOT NULL FOREIGN KEY REFERENCES TipoDocumento(Id),
    NumeroDocumento VARCHAR(50) NOT NULL,
    IdEncargado INT NOT NULL FOREIGN KEY REFERENCES Encargado(Id),
    IdTurno TINYINT NOT NULL FOREIGN KEY REFERENCES Turno(Id),
    IdAdministrador INT NOT NULL FOREIGN KEY REFERENCES Administrador(Id)
);
GO
-- TABLA Pago
CREATE TABLE Pago(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    IdAlumno INT NOT NULL FOREIGN KEY REFERENCES Alumno(Id),
    IdEncargado BIGINT NOT NULL,
    MontoPagar DECIMAL(10, 2) NOT NULL, -- Monto que debe pagar el alumno
    Multa DECIMAL(10, 2) NOT NULL DEFAULT 0, -- Multa que puede ingresar el administrador
    TotalPagado DECIMAL(10, 2) NOT NULL DEFAULT 0, -- Total pagado (MontoPagar + Multa)
    FechaRegistro DATE NOT NULL,
    IdAdministrador INT NOT NULL FOREIGN KEY REFERENCES Administrador(Id)
);
GO


CREATE TABLE Factura(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NumeroFactura INT NOT NULL,
    IdPago INT NOT NULL FOREIGN KEY REFERENCES Pago(Id),
    FechaDescarga DATETIME NOT NULL -- Fecha y hora de descarga de la factura
);
GO
-----TABLA FONDO
CREATE TABLE Fondo(
    Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    MontoTotal DECIMAL(10, 2) NOT NULL DEFAULT 0 -- Monto total acumulado
);
GO